Repository unb-mds/VIDAProject, pull requests merged in 2025-06, with the labels that each got.

#65 Feature spike similarity function
  vida_project_api/.gitignore
  vida_project_api/feature_spikeCreateEmbedding/voiceRecording.py
  vida_project_api/poetry.lock
  vida_project_api/pyproject.toml
Labels: backend, spike

#60 Libs required with poetry
  vida_project_api/.gitignore
  vida_project_api/poetry.lock
  vida_project_api/pyproject.toml
Labels: backend, spike

#72 migration.py integration
  vida_project_api/feature_spikePredownloading/voiceRecording.py
  vida_project_api/migration.py
Labels: backend

#73 Fixes
  vida_project_api/feature_spikePredownloading/voiceRecording.py
  vida_project_api/migration.py
Labels: bug, backend

#78 feat: atualiza readme e documentacoes
  CONTRIBUTING.md
  README.md
  docs/api.md
  docs/setup.md
Labels: documentation, enhancement

#81 chore: altera rotas de pastas da landing page e documentacoes do projeto
  docs/assets/asdsa.png
  docs/assets/background.png
  docs/assets/mockup.png
  docs/assets/old_background.png
  docs/assets/vida.png
  docs/index.html
  documentation/api.md
  documentation/meetings/sprint_0.md
  documentation/meetings/sprint_1.md
  documentation/reuniao.md
  documentation/setup.md
  documentation/spikeDocumentation/speechbrain_spike_doc.md
  documentation/studies/Design-tools/FigmaAndMiro.md
  documentation/studies/MFCC_GMM/mfcc_gmm.md
  documentation/studies/OOP/OOP.md
  documentation/studies/Software-Requirements/Software-Requirements.md
  documentation/studies/SystemDesign/arquiteturaradew.md
  documentation/studies/agileMethodologies/agil-methodologies.md
  documentation/studies/git-fundamentals/git.md
  documentation/studies/linuxMigration/overview_ubuntu_22_04.md
Labels: documentation
